// Test-only helper (Story 5.2): the committed sample sets' dancefloor segments,
// in the shape the read seam produces.
//
// Not part of any production path. `web/lib/sets/index.ts` reads real `segments`
// rows out of Supabase and resolves their boundary plays to ISO bounds; the unit
// tests need the same shape for the committed
// `recent-sets.fixture.json` sets, which have no cloud rows to read.
//
// `segments.fixture.json` is GENERATED by the real Rust detector
// (`agent/src-tauri/tests/segments_fixture.rs`) from those same fixture sets, and
// that test fails if it drifts. So these are genuinely the algorithm's own
// output, not hand-authored numbers a test could quietly be tuned to — the same
// data `supabase/seed.sql` seeds, resolved the same way.
//
// Regenerate with:
//   CURFEW_WRITE_SEGMENTS_FIXTURE=1 cargo test --manifest-path agent/src-tauri/Cargo.toml --test segments_fixture
//   node supabase/scripts/generate-seed.mjs
import segmentsFixture from "./segments.fixture.json";
import type { DancefloorSegment } from "./dancefloor";
import type { SyncPlay } from "./types";

type FixtureEntry = {
  external_id: string;
  segments: Array<{ type: string; first_position: number; last_position: number }>;
  idle_gaps: Array<{ start: number; end: number }>;
};

const byExternalId = new Map(
  (segmentsFixture as FixtureEntry[]).map((entry) => [entry.external_id, entry]),
);

/**
 * The dancefloor segments for one fixture set, as ISO bounds.
 *
 * Positions are resolved against the set's own `plays[]` — the same
 * position→boundary-play→`started_at` resolution `sync_set` and the read seam
 * perform, done here in TypeScript because a fixture has no database behind it.
 * A position that does not resolve to a timed play is dropped, mirroring the
 * RPC skipping an unresolvable entry.
 */
export function fixtureSegments(set: {
  external_id: string;
  plays: SyncPlay[];
}): DancefloorSegment[] {
  const entry = byExternalId.get(set.external_id);
  if (!entry) return [];
  const startedAt = new Map(set.plays.map((p) => [p.position, p.started_at]));
  return entry.segments.flatMap((s) => {
    // Mirrors production `toSegments()` (`web/lib/sets/index.ts`): only
    // `dancefloor` rows reach this shape. The generator can currently only ever
    // emit `dancefloor` (D-26), so this is unreachable today, but keeping the
    // filter here too closes a latent divergence between the test helper and
    // the read path it stands in for (code review finding, 2026-08-10).
    if (s.type !== "dancefloor") return [];
    const start = startedAt.get(s.first_position);
    const end = startedAt.get(s.last_position);
    if (start == null || end == null) return [];
    return [{ start, end }];
  });
}
