// Data-access seam for sets (Story 3.6 Task 4, AC-13 / SM-1).
//
// The dashboard and Set Detail import ONLY from here — never a fixture file, a
// Supabase client, or the wire envelope directly. Today it is backed by a
// committed real-data fixture (`recent-sets.fixture.json`, generated by
// `build-fixture.mjs` from the agent's re-derivation of the DJ's own sets); when
// the cloud read path lands, only the three function bodies below change to a
// Supabase query and every component keeps working unchanged (Decision A: the
// fixture is the day-one stand-in for the real read).
//
// All three are `async` so the signature already matches the eventual awaited
// Supabase reads — a component `await`s today and keeps awaiting later.
import fixture from "./recent-sets.fixture.json";
import type { SetRecord } from "./types";

// A mutable working copy of the fixture so the delete seam (AC-12) has somewhere
// to remove a row from — the honest "removes the row from the source" behavior
// for the fixture stage. This is process-local and resets on server restart;
// durable delete (local captured row + eventual cloud row) is Set Detail's job
// (Story 3.7), which calls `deleteSet` here. Cloning avoids mutating the
// imported module, which other requests share.
let store: SetRecord[] = structuredClone(fixture) as SetRecord[];

/**
 * Recent sets, newest-first (the fixture is already sorted by `started_at`
 * descending; the sort is repeated here so the contract holds regardless of
 * fixture order or a future unsorted Supabase result).
 */
export async function getRecentSets(): Promise<SetRecord[]> {
  return [...store].sort((a, b) => (b.started_at ?? "").localeCompare(a.started_at ?? ""));
}

/** One set by its `external_id`, or `null` if it does not exist (or was deleted). */
export async function getSetById(externalId: string): Promise<SetRecord | null> {
  return store.find((s) => s.external_id === externalId) ?? null;
}

/**
 * Removes a set from the data source (AC-12 — the removal path that replaces the
 * old "Skip"). Semantics: a hard delete, not a visibility flag. The calm confirm
 * UI and the deleted-state re-render live on Set Detail (Story 3.7); 3.6 only
 * needs the seam to support removal so that route is not blocked.
 */
export async function deleteSet(externalId: string): Promise<void> {
  store = store.filter((s) => s.external_id !== externalId);
}

export type { SetRecord } from "./types";
