// Data-access seam for sets (Story 3.6 Task 4, AC-13 / SM-1).
//
// The dashboard and Set Detail import ONLY from here — never a fixture file, a
// Supabase client, or the wire envelope directly. Today it is backed by a
// committed real-data fixture (`recent-sets.fixture.json`, generated by
// `build-fixture.mjs` from the agent's re-derivation of the DJ's own sets); when
// the cloud read path lands, only the three function bodies below change to a
// Supabase query and every component keeps working unchanged (Decision A: the
// fixture is the day-one stand-in for the real read).
//
// All three are `async` so the signature already matches the eventual awaited
// Supabase reads — a component `await`s today and keeps awaiting later.
//
// `getAgentStatus` (Story 3.9) is the one function here that is NOT
// fixture-backed: the agent-status heartbeat has no fixture stage, because the
// whole point of it is to report whether a real agent is really running. It
// reads Supabase directly through the same seam so the swap point stays in one
// file.
import fixture from "./recent-sets.fixture.json";
import addEventFixture from "./library-add-events.fixture.json";
import rosterFixture from "./library-roster.fixture.json";
import type { AgentStatusRow, AgentStatusSnapshot } from "./agentStatus";
import type { LibraryAddEvent } from "./libraryConversion";
import type { LibraryRosterSnapshot } from "./libraryRoster";
import type { SetRecord } from "./types";

// A mutable working copy of the fixture so the delete seam (AC-12) has somewhere
// to remove a row from — the honest "removes the row from the source" behavior
// for the fixture stage. This is process-local and resets on server restart;
// durable delete (local captured row + eventual cloud row) is Set Detail's job
// (Story 3.7), which calls `deleteSet` here. Cloning avoids mutating the
// imported module, which other requests share.
let store: SetRecord[] = structuredClone(fixture) as SetRecord[];

/**
 * Recent sets, newest-first (the fixture is already sorted by `started_at`
 * descending; the sort is repeated here so the contract holds regardless of
 * fixture order or a future unsorted Supabase result).
 */
export async function getRecentSets(): Promise<SetRecord[]> {
  return [...store].sort((a, b) => (b.started_at ?? "").localeCompare(a.started_at ?? ""));
}

/**
 * Library add-events plus the moment they were read (Story 4.2, FR-10).
 *
 * Carries the clock for the same reason `AgentStatusSnapshot` does: whether a
 * month-added cohort has finished its 90-day window is a question about *now*,
 * and `buildLibraryConversion` is a pure function that must be handed the time
 * rather than read it (Story 4.1's review: a `Date.now()` inside a "pure"
 * function is what made that suite machine-dependent). Reading it here also
 * keeps it out of a component render, which `react-hooks/purity` rightly
 * rejects.
 */
export interface LibraryAddEventSnapshot {
  events: LibraryAddEvent[];
  readAtMs: number;
}

/**
 * Every library add-event synced for this DJ (Story 4.2, FR-10) — the
 * denominator Style Evolution's library-conversion trend is computed against.
 *
 * Same seam discipline as `getRecentSets` above: fixture-backed today
 * (`build-library-fixture.mjs`, derived from the DJ's own captured plays),
 * swapped for a `library_track_events` select when the cloud read path lands.
 * RLS is owner-SELECT-only, so that query will need no `dj_id` filter either —
 * `auth.uid()` is the filter.
 *
 * Returns an empty list rather than throwing when nothing has ever synced: on
 * day one after this ships, EVERY DJ is in that state by construction (D-1's
 * baseline emits zero events), and it renders as the insufficient-history
 * copy, not as a broken page.
 */
export async function getLibraryAddEvents(): Promise<LibraryAddEventSnapshot> {
  return { events: addEventFixture as LibraryAddEvent[], readAtMs: Date.now() };
}

/**
 * The current DJ's library roster (Story 4.11, AD-22) — Tier A only
 * (title/artist; BPM/key/genre are Tier B, parked). Same seam discipline as
 * `getLibraryAddEvents` above: fixture-backed today
 * (`build-library-roster-fixture.mjs`, derived from the DJ's own catalogue
 * export), swapped for a `library_roster` select when the cloud read path
 * lands. RLS is owner-SELECT-only, so that query will need no `dj_id`
 * filter either — `auth.uid()` is the filter.
 *
 * No page reads `entries` yet (Story 4.4/4.10 are still `backlog`) — this
 * exists so those stories inherit a working read seam rather than needing
 * their own agent/shared/cloud work. `excludedNoIdentityCount`/
 * `totalCatalogueRows` DO have a consumer today (Story 4.3's meter, via
 * `unidentifiableTracksDisclosure`).
 */
export async function getLibraryRoster(): Promise<LibraryRosterSnapshot> {
  return rosterFixture as LibraryRosterSnapshot;
}

/** One set by its `external_id`, or `null` if it does not exist (or was deleted). */
export async function getSetById(externalId: string): Promise<SetRecord | null> {
  return store.find((s) => s.external_id === externalId) ?? null;
}

/**
 * Removes a set from the data source (AC-12 — the removal path that replaces the
 * old "Skip"). Semantics: a hard delete, not a visibility flag. The calm confirm
 * UI and the deleted-state re-render live on Set Detail (Story 3.7); 3.6 only
 * needs the seam to support removal so that route is not blocked.
 */
export async function deleteSet(externalId: string): Promise<void> {
  store = store.filter((s) => s.external_id !== externalId);
}

/**
 * The current DJ's agent-status heartbeat, stamped with the moment it was read
 * (Story 3.9, AC-1/AC-2 — AD-20).
 *
 * A `null` row covers every "we don't know" case, and the caller must treat
 * them all identically (render nothing): no session, no Supabase configured in
 * this checkout, no agent ever linked, or a read that failed. RLS
 * (owner-SELECT only) means the query can never return another DJ's row, so no
 * `dj_id` filter is needed or wanted here — `auth.uid()` is the filter.
 *
 * Deliberately resilient rather than gating, exactly like the dashboard's own
 * `getFirstName`: a status region that throws would take down a page whose
 * actual content (the DJ's sets) has nothing to do with the heartbeat.
 *
 * Staleness is NOT decided here — this returns the row as stored, plus the
 * clock. See `resolveAgentStatus` in `./agentStatus`, which owns that
 * definition.
 *
 * `@/lib/supabase/server` is imported lazily on purpose: it pulls in
 * `next/headers`, and a static import would bind that into every consumer of
 * this module, including the pure fixture reads above.
 */
export async function getAgentStatus(): Promise<AgentStatusSnapshot> {
  try {
    const { createClient } = await import("@/lib/supabase/server");
    const supabase = await createClient();
    const { data, error } = await supabase
      .from("agent_status")
      .select("sync_state, updated_at, agent_version")
      .maybeSingle();

    // A real misconfiguration (missing env, broken RLS) renders identically
    // to "no agent has ever linked" by design (see doc comment above), which
    // would otherwise let a genuine regression sit invisible indefinitely —
    // so it's still surfaced loudly in dev (Story 3.9 code review).
    if (error && process.env.NODE_ENV !== "production") {
      console.error("getAgentStatus: Supabase read failed, rendering as no-agent", error);
    }

    return { row: error ? null : ((data as AgentStatusRow | null) ?? null), readAtMs: Date.now() };
  } catch (err) {
    if (process.env.NODE_ENV !== "production") {
      console.error("getAgentStatus: unexpected failure, rendering as no-agent", err);
    }
    return { row: null, readAtMs: Date.now() };
  }
}

export type { SetRecord } from "./types";
export type { AgentStatusRow, AgentStatusSnapshot } from "./agentStatus";
export type { LibraryAddEvent } from "./libraryConversion";
export type { LibraryRosterEntry, LibraryRosterSnapshot } from "./libraryRoster";
